const SELECTORS = {
  signIn: {
    google: '#google-button',
    googleEmail: '#identifierId',
    linkedIn: '#linkedin-button',
    emailInput: '#email',
    emailButton: '#check-button',
    emailSignIn: '#password-sign-in',
    emailPassword: '#passwordField',
  },
  signUp: {
    emailInput: '#email',
    emailButton: '#check-button',
    toggleLink: '#signin-signup-toggle',
    firstName: '#firstName',
    lastName: '#lastName',
    password: '#passwordField',
    signUpButton: '#sign-up-button',
  },
  uploadResume: {
    appInput: 'input#APP-checkbox-false',
    webInput: 'input#WEB-checkbox-false',
    dataInput: 'input#DA-checkbox-false',
    nextCI: 'button#next-Career',
    nextRS: 'button#next-Relevant',
    nextSU: 'button#next-Current',
    nextUR: 'button#next-Upload',
    nextWA: 'button#next-Work',
    skillInput: "input[type='text']",
    addButton: "button[type='button']",
    currentUniversityInput: "div[type='text']",
    uploadResumeField: "input[type='file']",
    availableDaysInput: '#availableDays',
    workConditionInput: '#workingRights',
  },
  portal: {
    dashButton: 'button#logo-button',
    profileButton: "button[type='button']",
    profileImage: 'button#profile-button',
    profilePhoto: "button[type='button']",
    profilePhotoCancel: 'button#dialog-cancel',
    profilePhotoUpdate: 'button#dialog-save-false',
    profilePhotoInput: "input[type='file']",
    profileRouteButton: 'div#profile',
    jobsButton: 'div#jobs',
    assessmentButton: 'div#assessments',
    coursesButton: 'div#courses',
    contactUsButton: 'div#contactus',
    contactUsClose: "div[role='button']",
    FAQButton: 'a#FAQ',
    accountInfoButton: 'div#editaccountinfo',
    logOutButton: 'div#logout',
  },
  editAccInfo: {
    fName: '#firstName',
    lName: '#lastName',
    currUni: "div[type='text']",
    workCond: 'div#workingRights',
    availDays: 'div#availableDays',
    mobileNum: '#phoneNumber',
    promoCode: '#component-error',
    cancel: 'button#dialog-cancel',
    save: 'button#dialog-save-false',
  },
  courses: {
    getStarted: 'button#button-sdfsdfsdfsf',
    enrolledPageHeader: "h1[class='chapter-num']",
  },
  //Components
  activityLog: {
    icon: "button[type='button']",
    close: 'button#activitylogclose',
  },
  profileUploader: {
    button: 'button#profile-button',
    input: "input[type='file']",
    cancel: 'button#dialog-cancel',
    done: 'button#dialog-save-false',
    testImg: './test/testFiles/passiveAngrey.jpg',
  },
  sideBar: {
    dashboard: 'div#dashboard',
    profile: 'div#profile',
    jobs: 'div#jobs',
    assessments: 'div#assessments',
    courses: 'div#courses',
  },
  updateAccInfo: {
    button: 'div#updateaccountinfo',
    firstName: 'input#firstName',
    lastName: 'input#lastName',
    currentDegree: 'input#currentDegree',
    mobileNumber: 'input#mobileNumber',
    cancel: 'button#cancel',
    update: 'button#submit',
  },
  speedySignUp: {
    firstName: 'input#firstName',
    lastName: 'input#lastName',
    email: 'input#email',
    currentDegree: 'input#currentDegree',
    courses: 'input#course',
    jobs: 'input#job',
    signUp: 'button#submit',
    reset: 'button#reset',
  },
  courses: {
    button: 'div#Fixyourcar',
  },
};
const CRED = {
  signIn: {
    googleEmail: 'test2hats@gmail.com',
    email: 'test2hats@gmail.com',
    password: '2hatsSpiderman',
  },
  signUp: {
    firstName: 'Victor',
    lastName: 'Chan',
    email: 'test2hats@gmail.com',
    password: '2hatsSpiderman',
  },
};

const CONST = {
  screenshotPath: './test/screenshots',
  testPath: './test',
  sampleProfilePath: './test/passiveAngrey.jpg',
  sampleUserId: 'TO4P3eMVGGOben7jgUbekwNylQh1',
  urlPath: 'http://localhost:3333',
  protectedRedirectPath: 'http://localhost:3333/signin',
};

module.exports = { SELECTORS, CRED, CONST };
