# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:lts

pipelines:
  branches:
    SP3-staging:
      - step:
          caches:
            - node
            - globalnode
          script: # Modify the commands below to build your repository.
          # Run script to write config files
            - node scripts/deployconfig-staging
            # Add bit repo authentication
            - echo "//node.bit.dev/:_authToken = $BIT_NODE_TOKEN_INFO2HATS" >> .npmrc
            # Verify files are correct
            - cat .env
            - cat .firebaserc
            - cat firebase.json
            # Install dependencies
            - yarn global add firebase-tools
            - yarn install
            # Build
            - CI=false yarn build
            # Deploy to hosting
            - firebase deploy --token "$FIREBASE_TOKEN" --project staging2hats --non-interactive --public build --only hosting
    SP3-production:
      - step:
          caches:
          - node
          - globalnode
          script: # Modify the commands below to build your repository.
          # Run script to write config files
          - node scripts/deployconfig-production
          # Add bit repo authentication
          - echo "//node.bit.dev/:_authToken = $BIT_NODE_TOKEN_INFO2HATS" >> .npmrc
          # Verify files are correct
          - cat .env
          - cat .firebaserc
          - cat firebase.json
          # Install dependencies
          - yarn global add firebase-tools
          - yarn install
          # Build
          - CI=false yarn build
          # Deploy to hosting
          - firebase deploy --token "$FIREBASE_TOKEN" --project production2hats --non-interactive --public build --only hosting
definitions: 
   caches: 
     globalnode: /usr/local/lib/node_modules
