# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  branches:
    staging:
      - step:
          caches:
          - node
          - globalnode
          - localnode
          script: # Modify the commands below to build your repository.
          - npm install -g firebase-tools
          - npm install
          - yarn install
          - npm run build:staging
          - firebase deploy --token "$FIREBASE_TOKEN" --project dev2hats --non-interactive --public build --only hosting
definitions: 
   caches: 
     globalnode: /usr/local/lib/node_modules
     localnode: /opt/atlassian/pipelines/agent/build/functions/node_modules
