# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9

pipelines:
  branches:
    student-portal-3-revenge-of-the-hooks-react-reloaded-harder-better-faster-stronger:
      - step:
          caches:
          - node
          - globalnode
          - localnode
          script: # Modify the commands below to build your repository.
          - yarn global add firebase-tools
          - yarn install
          - CI=false yarn build
          - firebase deploy --token "$FIREBASE_TOKEN" --project staging2hats --non-interactive --public build --only hosting
    production:
      - step:
          caches:
          - node
          - globalnode
          - localnode
          script: # Modify the commands below to build your repository.
          - yarn global add firebase-tools
          - yarn install
          - CI=false yarn build
          - firebase deploy --token "$FIREBASE_TOKEN" --project production2hats --non-interactive --public build --only hosting
definitions: 
   caches: 
     globalnode: /usr/local/lib/node_modules
     localnode: /opt/atlassian/pipelines/agent/build/functions/node_modules
