# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:lts

pipelines:
  branches:
    SP3-staging:
      - step:
          caches:
            - node
            - globalnode
          script: # Modify the commands below to build your repository.
            - node scripts/deployconfig-staging
            - cat .env
            - cat .firebaserc
            - cat firebase.json
            - yarn global add firebase-tools
            # Add bit auth token from `$ npm login`
            - echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
            - echo "//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
            - yarn install
            - CI=false yarn build
            - firebase deploy --token "$FIREBASE_TOKEN" --project staging2hats --non-interactive --public build --only hosting
    SP3-production:
      - step:
          caches:
          - node
          - globalnode
          script: # Modify the commands below to build your repository.
          - node scripts/deployconfig-production
          - cat .env
          - cat .firebaserc
          - cat firebase.json
          - yarn global add firebase-tools
          - yarn install
          - CI=false yarn build
          - firebase deploy --token "$FIREBASE_TOKEN" --project production2hats --non-interactive --public build --only hosting
definitions: 
   caches: 
     globalnode: /usr/local/lib/node_modules
