export const UNIVERSITIES = [`University of Sydney\u2063\ (USYD)`,
`University of New South Wales\u2063\ (UNSW)`,
`Macquarie University\u2063\ (MU)`,
`University of Technology Sydney\u2063\ (UTS)`,
`Western Sydney University\u2063\ (WSU)`,
`University of Notre Dame\u2063\ (UND)`,
`University of Wollongong\u2063\ (UW)`,
`University of Newcastle\u2063\ (UN)`,
`Australian Catholic University\u2063\ (ACU)`,
`Harvard University`,
`Massachusetts Institute of Technology\u2063\ (MIT)`,
`University of California--Berkeley`,
`Stanford University`,
`University of Oxford`,
`University of Cambridge`,
`California Institute of Technology`,
`University of California--Los Angeles`,
`University of Chicago`,
`Columbia University`,
`Johns Hopkins University`,
`Imperial College London`,
`Princeton University`,
`University of Michigan`,
`University of Toronto`,
`University of Washington`,
`Yale University`,
`University of California--San Diego`,
`University of Pennsylvania`,
`Duke University`,
`University College London`,
`University of California--San Francisco`,
`Cornell University`,
`University of Tokyo`,
`Northwestern University`,
`Swiss Federal Institute of Technology Zurich`,
`University of Wisconsin--Madison`,
`University of California--Santa Barbara`,
`University of Minnesota--Twin Cities`,
`University of British Columbia`,
`University of Texas--Austin`,
`University of Melbourne`,
`University of North Carolina--Chapel Hill`,
`Ohio State University`,
`University of Illinois Urbana-Champaign`,
`New York University`,
`Boston University`,
`University of California--Davis`,
`Peking University`,
`University of Edinburgh`,
`Washington University`,
`University of Hong Kong`,
`University of Pittsburgh`,
`McGill University`,
`Pierre and Marie Curie University - Paris 6`,
`University of Queensland Australia`,
`University of Munich`,
`University of Manchester`,
`University of Southern California`,
`University of Maryland--College Park`,
`Pennsylvania State University`,
`KU Leuven`,
`University of Florida`,
`Karolinska Institute`,
`National University of Singapore`,
`Rutgers State University`,
`University of Colorado--Boulder`,
`Ruprecht Karl University Heidelberg`,
`Kyoto University`,
`Georgia Institute of Technology`,
`King's College London`,
`University of California--Santa Cruz`,
`University of Arizona`,
`University of Copenhagen`,
`University of California--Irvine`,
`Tsinghua University`,
`Utrecht University`,
`Purdue University`,
`Université Paris-Sud`,
`Rockefeller University`,
`Australian National University (ANU)`,
`Seoul National University`,
`Carnegie Mellon University`,
`Leiden University`,
`Michigan State University`,
`École Polytechnique Fédérale de Lausanne`,
`Humboldt University of Berlin`,
`Universidade de São Paulo`,
`University of Amsterdam`,
`Free University of Berlin`,
`University of Bristol`,
`University of Zurich`,
`Emory University`,
`Erasmus University Rotterdam`,
`Texas A&M University--College Station`,
`Ghent University`,
`Monash University`,
`Rice University`,
`Vanderbilt University`,
`London School of Hygiene & Tropical Medicine`,
`Tufts University`,
`University of Göttingen`,
`Technical University of Munich`,
`University of Barcelona`,
`University of Montreal`,
`Lund University`,
`University of Groningen`,
`University of Helsinki`,
`Mayo Clinic`,
`University of Geneva`,
`University of Virginia`,
`Weizmann Institute of Science`,
`National Taiwan University`,
`Brown University`,
`Uppsala University`,
`Fudan University`,
`University of Alberta`,
`VU University Amsterdam`,
`Osaka University`,
`University of Glasgow`,
`University of Western Australia`,
`Indiana University--Bloomington`,
`University of Massachusetts--Amherst`,
`Joseph Fourier University - Grenoble 1`,
`Université Paris Diderot - Paris 7`,
`Aarhus University`,
`Chinese University of Hong Kong`,
`University of Rochester`,
`University of Birmingham`,
`University of Iowa`,
`Radboud University Nijmegen`,
`University of Basel`,
`Nanyang Technological University`,
`University of Bern`,
`University of California--Riverside`,
`Zhejiang University`,
`Hong Kong University of Science and Technology`,
`Tohoku University`,
`Stony Brook University--SUNY`,
`University of Leeds`,
`University of Southampton`,
`Wageningen University and Research Center`,
`University of Hamburg`,
`University of Oslo`,
`Case Western Reserve University`,
`University of Sheffield`,
`Sapienza University of Rome`,
`University of Bonn`,
`McMaster University`,
`Stockholm University`,
`Arizona State University`,
`University of Science and Technology of China`,
`University of Utah`,
`University of Bologna`,
`University of Padua`,
`Shanghai Jiao Tong University`,
`Tel Aviv University`,
`University of Liverpool`,
`University of Cape Town`,
`Hebrew University of Jerusalem`,
`University of Nottingham`,
`Karlsruhe Institute of Technology`,
`Iowa State University`,
`University of Milan`,
`Korea University`,
`University of Maryland--Baltimore`,
`Queen Mary University of London`,
`Autonomous University of Barcelona`,
`Baylor College of Medicine`,
`Icahn School of Medicine at Mount Sinai`,
`University of Freiburg`,
`Middle East Technical University`,
`Tokyo Institute of Technology`,
`University of Texas Southwestern Medical Center--Dallas`,
`Nagoya University`,
`University of Illinois Chicago`,
`University of Miami`,
`Université de Strasbourg`,
`University of Tennessee--Knoxville`,
`Florida State University`,
`Pohang University of Science and Technology`,
`RWTH Aachen University`,
`University of Auckland`,
`Maastricht University`,
`Charite - Medical University of Berlin`,
`Eberhard Karls University Tübingen`,
`Charles University in Prague`,
`Goethe University Frankfurt`,
`Korea Advanced Institute of Science and Technology`,
`University of Alabama--Birmingham`,
`University of Warwick`,
`University of Notre Dame`,
`Aix-Marseille Université`,
`Nanjing University`,
`Technical University of Denmark`,
`Cardiff University`,
`Delft University of Technology`,
`Durham University`,
`University of Adelaide`,
`University of Münster`,
`École Polytechnique`,
`Newcastle University`,
`University of Ottawa`,
`Lomonosov Moscow State University`,
`Johannes Gutenberg University of Mainz`,
`Royal Institute of Technology`,
`University of Vienna`,
`University of Cincinnati`,
`École Normale Supérieure, Paris`,
`University of Texas Health Science Center--Houston`,
`University of Calgary`,
`University of New Mexico`,
`University of Georgia`,
`University of Turin`,
`University of Lausanne`,
`University of Kansas`,
`University of St Andrews`,
`Autonomous University of Madrid`,
`Trinity College Dublin`,
`University of Erlangen Nuremberg`,
`North Carolina State University`,
`Technical University of Dresden`,
`Université Claude Bernard Lyon 1`,
`City University of Hong Kong`,
`University of Würzburg`,
`Université Paul Sabatier - Toulouse 3`,
`University of Colorado--Denver`,
`Sun Yat-sen University`,
`University of Antwerp`,
`Université Paris Descartes - Paris V`,
`Yonsei University`,
`Northeastern University`,
`University of Cologne`,
`University of Gothenburg`,
`Université Montpellier 2`,
`Sungkyunkwan University`,
`Lancaster University`,
`Université Catholique de Louvain`,
`University of Bergen`,
`University of Western Ontario`,
`Yeshiva University`,
`Laval University`,
`Hong Kong Polytechnic University`,
`Istanbul Teknik Üniversitesi`,
`Technion Israel Institute of Technology`,
`Université Libre de Bruxelles`,
`University of Kiel`,
`University of Pisa`,
`Colorado State University`,
`Dartmouth College`,
`University of Otago`,
`Hokkaido University`,
`University of Aberdeen`,
`University of Waterloo`,
`Universidade Federal do Rio de Janeiro`,
`University of Tsukuba`,
`Virginia Tech`,
`Kyushu University`,
`Oregon State University`,
`University of Exeter`,
`University of Nebraska--Lincoln`,
`Universidade Estadual de Campinas`,
`University of Leicester`,
`University of Naples Federico II`,
`University of Valencia`,
`Georgetown University`,
`University of York`,
`Technical University of Berlin`,
`University of Buenos Aires`,
`University of Florence`,
`University of South Carolina`,
`University of Trieste`,
`Universidade de Lisboa`,
`University of Texas--Dallas`,
`Oregon Health and Science University`,
`University of Kentucky`,
`University of Oregon`,
`University of Ulm`,
`University of Witwatersrand`,
`Pompeu Fabra University`,
`University of Connecticut`,
`University of East Anglia`,
`University of Sussex`,
`University College Dublin`,
`Wayne State University`,
`Eindhoven University of Technology`,
`University of Rome Tor Vergata`,
`University of Warsaw`,
`George Washington University`,
`National Tsing Hua University`,
`University of Pavia`,
`University of Oklahoma`,
`Waseda University`,
`University of Massachusetts--Worcester`,
`Simon Fraser University`,
`Jagiellonian University`,
`University of Missouri--Columbia`,
`Complutense University of Madrid`,
`Thomas Jefferson University`,
`National and Kapodistrian University of Athens`,
`University of Delaware`,
`Huazhong University of Science and Technology`,
`National Autonomous University of Mexico`,
`Ruhr University Bochum`,
`Queen's University`,
`Beijing Normal University`,
`University of South Florida`,
`Wake Forest University`,
`University of Reading`,
`Wuhan University`,
`University of Innsbruck`,
`Bilkent University`,
`University of Houston`,
`Friedrich Schiller University of Jena`,
`Norwegian University of Science and Technology`,
`Medical University of Vienna`,
`University of Granada`,
`City University of New York (CUNY) System`,
`Vienna University of Technology`,
`Nankai University`,
`Queen's University Belfast`,
`University of Leipzig`,
`Virginia Commonwealth University`,
`Grenoble Institute of Technology`,
`Universidade Federal de Minas Gerais`,
`University of Delhi`,
`University of Victoria`,
`Vrije Universiteit Brussel`,
`Macquarie University`,
`University of Hawaii--Manoa`,
`Indian Institute of Science`,
`National Cheng Kung University`,
`Umeå University`,
`Université Bordeaux 1`,
`Washington State University`,
`London School of Economics and Political Science`,
`University of Dundee`,
`University of Mississippi`,
`University of Perugia`,
`University of Duisburg-Essen`,
`Universidade do Porto`,
`Hannover Medical School`,
`Darmstadt University of Technology`,
`Heinrich Heine University Düsseldorf`,
`Justus Liebig University Giessen`,
`Université of Liège`,
`Harbin Institute of Technology`,
`Kansas State University`,
`University of Twente`,
`University of Milan-Bicocca`,
`Dalhousie University`,
`Hiroshima University`,
`Shandong University`,
`Baylor University`,
`University of Ljubljana`,
`University of Regensburg`,
`University of Manitoba`,
`Polytechnic University of Milan`,
`Queensland University of Technology`,
`Université de Savoie`,
`University of Genoa`,
`Vita-Salute San Raffaele University`,
`Xi'an Jiaotong University`,
`Tulane University`,
`University at Albany--SUNY`,
`Curtin University of Technology`,
`University of Tehran`,
`Xiamen University`,
`University of Stuttgart`,
`Keio University`,
`James Cook University`,
`National Central University`,
`Union School of Public Health - Peking Union Medical College`,
`Universidade Estadual Paulista`,
`National Chiao Tung University`,
`Rensselaer Polytechnic Institute`,
`Czech Technical University in Prague`,
`Stellenbosch University`,
`Universidade Federal do Rio Grande do Sul`,
`Tongji University`,
`Aalto University`,
`University of Turku`,
`Okayama University`,
`Sharif University of Technology`,
`Syracuse University`,
`Université Montpellier 1`,
`Temple University`,
`University of Alabama--Tuscaloosa`,
`Chalmers University of Technology`,
`University of Canterbury`,
`York University`,
`University of Bari`,
`University of Bremen`,
`Linköping University`,
`University of Belgrade`,
`Boston College`,
`China Agricultural University`,
`University of Guelph`,
`Aristotle University of Thessaloniki`,
`Université de Versailles Saint-Quentin-en-Yvelines`,
`University of Tasmania`,
`Drexel University`,
`University of Southern Denmark`,
`Southeast University`,
`Swedish University of Agricultural Sciences`,
`University of Siena`,
`Dalian University of Technology`,
`George Mason University`,
`Indiana University-Purdue University--Indianapolis`,
`Kobe University`,
`Indian Institute of Technology Bombay`,
`Pontificia Universidad Católica de Chile`,
`Université de Rennes 1`,
`Jilin University`,
`Dortmund University of Technology`,
`Philipps University of Marburg`,
`Polytechnic University of Catalonia`,
`University of Bath`,
`University of Crete`,
`University of Santiago de Compostela`,
`Medical University of South Carolina`,
`University of Central Florida`,
`Griffith University`,
`University of KwaZulu-Natal`,
`University of Trento`,
`University at Buffalo--SUNY`,
`University of Eastern Finland`,
`University College Cork`,
`Universiti Malaya`,
`Deakin University`,
`Kyungpook National University`,
`Brunel University`,
`Sichuan University`,
`ENS de Lyon`,
`Hanyang University`,
`Universidade de Coimbra`,
`Ben-Gurion University of the Negev`,
`University of Potsdam`,
`Saint Petersburg State University`,
`University of Texas--Arlington`,
`East China Normal University`,
`Medical University of Innsbruck`,
`University of Konstanz`,
`Oklahoma State University - Stillwater`,
`Texas Tech University`,
`University of Hannover`,
`University of Udine`,
`University of Zaragoza`,
`Cairo University`,
`Universidade Federal de São Paulo`,
`Université Nice Sophia Antipolis`,
`Saarland University`,
`University of Texas Medical Branch--Galveston`,
`Eotvos Lorand University`,
`Polytechnic University of Valencia`,
`South China University of Technology`,
`Universidade do Estado do Rio de Janeiro`,
`University of Technology Sydney`,
`Ege University`,
`Ewha Womans University`,
`Lanzhou University`,
`Mahidol University`,
`Universidad de Chile`,
`Florida International University`,
`University of Surrey`,
`Bielefeld University`,
`Medical College of Wisconsin`,
`Saint Louis University`,
`Tokyo Medical and Dental University`,
`Tokyo Metropolitan University`,
`Roma Tre University`,
`University of Tromsø`,
`Gwangju Institute of Science and Technology`,
`University of Catania`,
`University of Tartu`,
`Loughborough University`,
`China University of Geosciences`,
`Isfahan University of Technology`,
`Chiba University`,
`King Saud University`,
`National Technical National and Kapodistrian University of Athens`,
`Tilburg University`,
`University of Saskatchewan`,
`Comenius University in Bratislava`,
`University of Bayreuth`,
`University of South Australia`,
`Ankara University`,
`Massey University`,
`University of Louisville`,
`Catholic University of the Sacred Heart`,
`Indian Institute of Technology Kharagpur`,
`Universidade de Aveiro`,
`University of Vermont`,
`Palacky University Olomouc`,
`University of Graz`,
`University of Sevilla`,
`University of Zagreb`,
`Hacettepe University`,
`San Diego State University`,
`Istanbul University`,
`Université de Lille I`,
`Kyung Hee University`,
`Quaid I Azam University`,
`University of Jyväskylä`,
`University of Lorraine`,
`University of Strathclyde`]
